# Generated by Django 5.1.6 on 2025-02-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatmessage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='session_id',
            field=models.IntegerField(),
        ),
    ]
